### ISSUE TITLE
[Feature] Reranking Plugin Release

### ISSUE THREAD

**Issue by macohen** [opensearch-project/search-processor#27]
We're planning to include the reranking plugin in the 2.5.0 release. This tracks our progress to turn the search-relevance repo into a single plugin repo.

**Comment by macohen** [comment]
- [x] Enable Backporting
- [x] Semver Labels 
- [x] Coverage Report
- [ ] Automated Version Bumps
- [x] https://github.com/opensearch-project/search-processor/issues/31
- [ ] https://github.com/opensearch-project/search-processor/issues/52
<del> - [ ] https://github.com/opensearch-project/search-processor/issues/46 </del>
- [ ] https://github.com/opensearch-project/search-processor/issues/45

**Comment by msfroh** [comment]
Improving test coverage is tracked in https://github.com/opensearch-project/search-processor/issues/31

**Comment by macohen** [comment]
We are delaying decision on how to release this repo as a plugin so closing this for now.
