### ISSUE TITLE
[META] Update github workflow - autoclosed

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/search-processor#55]
Update github workflow to resolve several issues:

- [x] 1. Action failed in backport PR due to static DCO check - remove the extra dco.yml
- [x] 2. PR_stats failed due to some issue from github graphQL, may related to permission setup
- [x] 3. PR Template includes link to knn plugin

We need to resolve 2. first since 1. and 3. are depend on it

**Comment by macohen** [comment]
going to disable pr_stats.yml until I understand it better.
